language: go

go: 
  - 1.10.x

install:
  - go get -v golang.org/x/tools/cmd/goimports
  - go get -v github.com/mitchellh/gox
  - mkdir release
  - cd release && gox -arch 'amd64' -os 'linux windows darwin' ../cmd/...

before_script:
  - cd $TRAVIS_BUILD_DIR
  - GO_FILES=$(find . -type f -name '*.go' -not -path "./vendor/*")

script:
  - test -z $(goimports -d $GO_FILES) # this test asserts import ordering
  - test -z $(gofmt -s -d $GO_FILES)
  - go test -v ./...

before_deploy:
  - git tag "$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)"

deploy:
  provider: releases
  api_key:
    secure: iz8dN3O82B0+EX0id47/1lRCAj2hiekPi1zNKz76t3mtbitcbbxGWd7s5rmld9WhZpZh12h+SPWNVOw/1GJ1ZsrCXy3hjEXvetYlFPxk49I27iXP68sLkYCL1KnhIGAedVAPOZmc5mz0uBkhyaQ6BOrPamy7j8QzNoYzgqOxslHqewok6jTuMlBfHaIip8xFtu3WpX3BslVIch7pM1/WZid4iAOrStmpXkfA2ri/L/kqTSfoqdVQ1sxKsJHn+34TgnpC6L+8cX7Rj0IyffqKtl6OVnxWclUKqyhNmbB07eALl/4DhiFW16q4D1kZTjKSo+lt010tR3OcoI6oqENdp6fzPe2xK7vDaeiHdqPpQv9hbJNK7Uoy0KR/OIoExUMcv5rs3adLfqwGE5rumOMTe+rB0rO4dpPfuK8/5f+y+3p9IxgroM1IDAno+FKGizv32Irg40+DMohSqGTFO/KTgg+QQxFWqHNfP/uBnpHCb0ijizZyK7ZrJxYks4u9/yumiSx9zY6azp9Ydni6+EXt4liqXFW6G3K6zzB84yNYp8w9n8ljQBQh8o5v5Fyu9gehJGKw4SSH4fvAvmw992pflRAd1GRBpnuP5FwChCn92UOfzSQXSjoqigmgCajN44tpzFZr+7D/ysneXYAMmVPA45JHG0EGE7WN2DKSsLgxAQA=
  file_glob: true
  file: release/*
  skip_cleanup: true
  on:
    branch: master