version: "{build}"
shallow_clone: true
clone_folder: c:\gopath\src\github.com\sourcegraph\cloneproxy
skip_branch_with_pr: true

environment:
  GOPATH: c:\gopath

install:
  - set PATH=%GOPATH%\bin;c:\go\bin;%PATH%
  - go version

build: off

test_script:
  - go test -v ./...
